version: '3.3'
services:

  yeti:
    build:
      context: ../../
      dockerfile: ./extras/docker/Dockerfile
    ports:
      - "8080:8080"
    command: ['uwsgi-http']
    depends_on:
      - redis
      - mongodb

  feeds:
    build:
      context: ../../
      dockerfile: ./extras/docker/Dockerfile
    command: ['feeds']
    depends_on:
      - redis
      - mongodb
      - yeti
    environment:
      - TLDEXTRACT_CACHE=/tmp/tldextract.cache

  analytics:
    build:
      context: ../../
      dockerfile: ./extras/docker/Dockerfile
    command: ['analytics']
    depends_on:
      - redis
      - mongodb
      - yeti
    environment:
      - TLDEXTRACT_CACHE=/tmp/tldextract.cache

  beat:
    build:
      context: ../../
      dockerfile: ./extras/docker/Dockerfile
    command: ['beat']
    depends_on:
      - redis
      - mongodb
      - yeti
      - feeds
      - analytics
      - exports

  exports:
    build:
      context: ../../
      dockerfile: ./extras/docker/Dockerfile
    command: ['exports']
    depends_on:
      - redis
      - mongodb
      - yeti

  oneshot:
    build:
      context: ../../
      dockerfile: ./extras/docker/Dockerfile
    command: ['oneshot']
    depends_on:
      - redis
      - mongodb
      - yeti

  redis:
    image: redis:latest

  mongodb:
    image: mongo:4.0.12
    environment:
      - MONGO_LOG_DIR=/dev/null
    command: mongod
